//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobleTimesApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Demo_LearningEntities : DbContext
    {
        public Demo_LearningEntities()
            : base("name=Demo_LearningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sale> sales { get; set; }
        public virtual DbSet<tbl_Employees> tbl_Employees { get; set; }
        public virtual DbSet<tbl_Magic> tbl_Magic { get; set; }
        public virtual DbSet<tbl_mailingaddress> tbl_mailingaddress { get; set; }
        public virtual DbSet<tbl_marks> tbl_marks { get; set; }
        public virtual DbSet<tbl_PrimaryKey> tbl_PrimaryKey { get; set; }
        public virtual DbSet<tbl_students> tbl_students { get; set; }
        public virtual DbSet<tbl_physicaladdress> tbl_physicaladdress { get; set; }
    }
}
