//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobleTimesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_students
    {
        public int ID { get; set; }
        public string Student_Name { get; set; }
        public Nullable<int> Roll_Number { get; set; }
        public string Course { get; set; }
    }
}
