//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobleTimesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_physicaladdress
    {
        public int Address_ID { get; set; }
        public Nullable<int> EmployeeNumber { get; set; }
        public string HouseNumber { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
    }
}
