//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobleTimesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PrimaryKey
    {
        public decimal ID { get; set; }
        public string First_Name { get; set; }
    }
}
